// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.1
// source: kv/protos/speedrate.proto

package speedrate_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User_PhoneType int32

const (
	User_MOBILE User_PhoneType = 0
	User_HOME   User_PhoneType = 1
	User_WORK   User_PhoneType = 2
)

// Enum value maps for User_PhoneType.
var (
	User_PhoneType_name = map[int32]string{
		0: "MOBILE",
		1: "HOME",
		2: "WORK",
	}
	User_PhoneType_value = map[string]int32{
		"MOBILE": 0,
		"HOME":   1,
		"WORK":   2,
	}
)

func (x User_PhoneType) Enum() *User_PhoneType {
	p := new(User_PhoneType)
	*p = x
	return p
}

func (x User_PhoneType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (User_PhoneType) Descriptor() protoreflect.EnumDescriptor {
	return file_kv_protos_speedrate_proto_enumTypes[0].Descriptor()
}

func (User_PhoneType) Type() protoreflect.EnumType {
	return &file_kv_protos_speedrate_proto_enumTypes[0]
}

func (x User_PhoneType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use User_PhoneType.Descriptor instead.
func (User_PhoneType) EnumDescriptor() ([]byte, []int) {
	return file_kv_protos_speedrate_proto_rawDescGZIP(), []int{0, 0}
}

type Rating_RatingType int32

const (
	Rating_NEGATIVE Rating_RatingType = 0
	Rating_NEUTRAL  Rating_RatingType = 1
	Rating_POSITIVE Rating_RatingType = 2
)

// Enum value maps for Rating_RatingType.
var (
	Rating_RatingType_name = map[int32]string{
		0: "NEGATIVE",
		1: "NEUTRAL",
		2: "POSITIVE",
	}
	Rating_RatingType_value = map[string]int32{
		"NEGATIVE": 0,
		"NEUTRAL":  1,
		"POSITIVE": 2,
	}
)

func (x Rating_RatingType) Enum() *Rating_RatingType {
	p := new(Rating_RatingType)
	*p = x
	return p
}

func (x Rating_RatingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Rating_RatingType) Descriptor() protoreflect.EnumDescriptor {
	return file_kv_protos_speedrate_proto_enumTypes[1].Descriptor()
}

func (Rating_RatingType) Type() protoreflect.EnumType {
	return &file_kv_protos_speedrate_proto_enumTypes[1]
}

func (x Rating_RatingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Rating_RatingType.Descriptor instead.
func (Rating_RatingType) EnumDescriptor() ([]byte, []int) {
	return file_kv_protos_speedrate_proto_rawDescGZIP(), []int{1, 0}
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id             string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"` // Unique ID number for this person.
	Email          string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phones         []*User_PhoneNumber    `protobuf:"bytes,4,rep,name=phones,proto3" json:"phones,omitempty"`
	AccountCreated *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=account_created,json=accountCreated,proto3" json:"account_created,omitempty"`
	LastUpdated    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kv_protos_speedrate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_kv_protos_speedrate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_kv_protos_speedrate_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPhones() []*User_PhoneNumber {
	if x != nil {
		return x.Phones
	}
	return nil
}

func (x *User) GetAccountCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.AccountCreated
	}
	return nil
}

func (x *User) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

type Rating struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RatingType  Rating_RatingType `protobuf:"varint,1,opt,name=ratingType,proto3,enum=speedrate.v1.Rating_RatingType" json:"ratingType,omitempty"`
	RatingText  string            `protobuf:"bytes,2,opt,name=ratingText,proto3" json:"ratingText,omitempty"`
	RatingImage []byte            `protobuf:"bytes,3,opt,name=ratingImage,proto3" json:"ratingImage,omitempty"`
	RatingVideo []byte            `protobuf:"bytes,4,opt,name=ratingVideo,proto3" json:"ratingVideo,omitempty"`
	Lifecycle   string            `protobuf:"bytes,5,opt,name=Lifecycle,proto3" json:"Lifecycle,omitempty"`
	UserID      string            `protobuf:"bytes,6,opt,name=UserID,proto3" json:"UserID,omitempty"`
}

func (x *Rating) Reset() {
	*x = Rating{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kv_protos_speedrate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rating) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rating) ProtoMessage() {}

func (x *Rating) ProtoReflect() protoreflect.Message {
	mi := &file_kv_protos_speedrate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rating.ProtoReflect.Descriptor instead.
func (*Rating) Descriptor() ([]byte, []int) {
	return file_kv_protos_speedrate_proto_rawDescGZIP(), []int{1}
}

func (x *Rating) GetRatingType() Rating_RatingType {
	if x != nil {
		return x.RatingType
	}
	return Rating_NEGATIVE
}

func (x *Rating) GetRatingText() string {
	if x != nil {
		return x.RatingText
	}
	return ""
}

func (x *Rating) GetRatingImage() []byte {
	if x != nil {
		return x.RatingImage
	}
	return nil
}

func (x *Rating) GetRatingVideo() []byte {
	if x != nil {
		return x.RatingVideo
	}
	return nil
}

func (x *Rating) GetLifecycle() string {
	if x != nil {
		return x.Lifecycle
	}
	return ""
}

func (x *Rating) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type User_PhoneNumber struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number string         `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Type   User_PhoneType `protobuf:"varint,2,opt,name=type,proto3,enum=speedrate.v1.User_PhoneType" json:"type,omitempty"`
}

func (x *User_PhoneNumber) Reset() {
	*x = User_PhoneNumber{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kv_protos_speedrate_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User_PhoneNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User_PhoneNumber) ProtoMessage() {}

func (x *User_PhoneNumber) ProtoReflect() protoreflect.Message {
	mi := &file_kv_protos_speedrate_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User_PhoneNumber.ProtoReflect.Descriptor instead.
func (*User_PhoneNumber) Descriptor() ([]byte, []int) {
	return file_kv_protos_speedrate_proto_rawDescGZIP(), []int{0, 0}
}

func (x *User_PhoneNumber) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *User_PhoneNumber) GetType() User_PhoneType {
	if x != nil {
		return x.Type
	}
	return User_MOBILE
}

var File_kv_protos_speedrate_proto protoreflect.FileDescriptor

var file_kv_protos_speedrate_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6b, 0x76, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x73, 0x70, 0x65, 0x65,
	0x64, 0x72, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x73, 0x70, 0x65,
	0x65, 0x64, 0x72, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x82, 0x03, 0x0a, 0x04, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x36, 0x0a,
	0x06, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x73, 0x70, 0x65, 0x65, 0x64, 0x72, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x2e, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x06, 0x70,
	0x68, 0x6f, 0x6e, 0x65, 0x73, 0x12, 0x43, 0x0a, 0x0f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0e, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x3d, 0x0a, 0x0c, 0x6c, 0x61,
	0x73, 0x74, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x6c, 0x61,
	0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x1a, 0x57, 0x0a, 0x0b, 0x50, 0x68, 0x6f,
	0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x30, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c,
	0x2e, 0x73, 0x70, 0x65, 0x65, 0x64, 0x72, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x2e, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x22, 0x2b, 0x0a, 0x09, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0a, 0x0a, 0x06, 0x4d, 0x4f, 0x42, 0x49, 0x4c, 0x45, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x48,
	0x4f, 0x4d, 0x45, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x57, 0x4f, 0x52, 0x4b, 0x10, 0x02, 0x22,
	0x9a, 0x02, 0x0a, 0x06, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x3f, 0x0a, 0x0a, 0x72, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f,
	0x2e, 0x73, 0x70, 0x65, 0x65, 0x64, 0x72, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x0a, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x72,
	0x61, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x65, 0x78, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x72,
	0x61, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0b, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0b, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12,
	0x1c, 0x0a, 0x09, 0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x35, 0x0a, 0x0a, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x45, 0x47, 0x41, 0x54, 0x49, 0x56, 0x45, 0x10,
	0x00, 0x12, 0x0b, 0x0a, 0x07, 0x4e, 0x45, 0x55, 0x54, 0x52, 0x41, 0x4c, 0x10, 0x01, 0x12, 0x0c,
	0x0a, 0x08, 0x50, 0x4f, 0x53, 0x49, 0x54, 0x49, 0x56, 0x45, 0x10, 0x02, 0x42, 0x29, 0x5a, 0x27,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x6f, 0x6f, 0x6b, 0x6e,
	0x69, 0x67, 0x68, 0x74, 0x2f, 0x72, 0x65, 0x73, 0x74, 0x79, 0x2f, 0x73, 0x70, 0x65, 0x65, 0x64,
	0x72, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kv_protos_speedrate_proto_rawDescOnce sync.Once
	file_kv_protos_speedrate_proto_rawDescData = file_kv_protos_speedrate_proto_rawDesc
)

func file_kv_protos_speedrate_proto_rawDescGZIP() []byte {
	file_kv_protos_speedrate_proto_rawDescOnce.Do(func() {
		file_kv_protos_speedrate_proto_rawDescData = protoimpl.X.CompressGZIP(file_kv_protos_speedrate_proto_rawDescData)
	})
	return file_kv_protos_speedrate_proto_rawDescData
}

var file_kv_protos_speedrate_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_kv_protos_speedrate_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kv_protos_speedrate_proto_goTypes = []interface{}{
	(User_PhoneType)(0),           // 0: speedrate.v1.User.PhoneType
	(Rating_RatingType)(0),        // 1: speedrate.v1.Rating.RatingType
	(*User)(nil),                  // 2: speedrate.v1.User
	(*Rating)(nil),                // 3: speedrate.v1.Rating
	(*User_PhoneNumber)(nil),      // 4: speedrate.v1.User.PhoneNumber
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_kv_protos_speedrate_proto_depIdxs = []int32{
	4, // 0: speedrate.v1.User.phones:type_name -> speedrate.v1.User.PhoneNumber
	5, // 1: speedrate.v1.User.account_created:type_name -> google.protobuf.Timestamp
	5, // 2: speedrate.v1.User.last_updated:type_name -> google.protobuf.Timestamp
	1, // 3: speedrate.v1.Rating.ratingType:type_name -> speedrate.v1.Rating.RatingType
	0, // 4: speedrate.v1.User.PhoneNumber.type:type_name -> speedrate.v1.User.PhoneType
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_kv_protos_speedrate_proto_init() }
func file_kv_protos_speedrate_proto_init() {
	if File_kv_protos_speedrate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kv_protos_speedrate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kv_protos_speedrate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rating); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kv_protos_speedrate_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User_PhoneNumber); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kv_protos_speedrate_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kv_protos_speedrate_proto_goTypes,
		DependencyIndexes: file_kv_protos_speedrate_proto_depIdxs,
		EnumInfos:         file_kv_protos_speedrate_proto_enumTypes,
		MessageInfos:      file_kv_protos_speedrate_proto_msgTypes,
	}.Build()
	File_kv_protos_speedrate_proto = out.File
	file_kv_protos_speedrate_proto_rawDesc = nil
	file_kv_protos_speedrate_proto_goTypes = nil
	file_kv_protos_speedrate_proto_depIdxs = nil
}
